{
  pkgs,
}:
let
  androidEnv = pkgs.androidenv;

  sdkArgs = {
    includeSystemImages = true;
    includeEmulator = true;
    includeNDK = true;

    abiVersions = [
      "armeabi-v7a"
      "arm64-v8a"
      "x86_64"
    ];

    platformVersions = [ "35" ];
    systemImageTypes = [ "default" ];

    # Accepting more licenses declaratively:
    extraLicenses = [
      # Already accepted for you with the global accept_license = true or
      # licenseAccepted = true on androidenv.
      # "android-sdk-license"

      # These aren't, but are useful for more uncommon setups.
      "android-sdk-preview-license"
      "android-googletv-license"
      "android-sdk-arm-dbt-license"
      "google-gdk-license"
      "intel-android-extra-license"
      "intel-android-sysimage-license"
      "mips-android-sysimage-license"
    ];
  };

  androidComposition = androidEnv.composeAndroidPackages sdkArgs;
  androidEmulator = androidEnv.emulateApp {
    name = "android-sdk-emulator-demo";
    configOptions = {
      "hw.keyboard" = "yes";
    };
    sdkExtraArgs = sdkArgs;
  };
  androidSdk = androidComposition.androidsdk;
  platformTools = androidComposition.platform-tools;
  jdk = pkgs.jdk;
in
pkgs.mkShell rec {
  name = "androidenv";
  packages = [
    androidSdk
    platformTools
    androidEmulator
    jdk
  ];

  LANG = "C.UTF-8";
  LC_ALL = "C.UTF-8";
  JAVA_HOME = jdk.home;

  # Note: ANDROID_HOME is deprecated. Use ANDROID_SDK_ROOT.
  ANDROID_HOME = ANDROID_SDK_ROOT;
  ANDROID_SDK_ROOT = "${androidSdk}/libexec/android-sdk";
  ANDROID_NDK_ROOT = "${ANDROID_SDK_ROOT}/ndk-bundle";

  # from https://old.reddit.com/r/NixOS/comments/1f92ph6/anyone_know_how_to_run_an_android_emulator_in/luqp500/
  _JAVA_AWT_WM_NONREPARENTING = 1;
  AWT_TOOLKIT = "MToolkit";
  GDK_BACKEND = "x11";
  QT_QPA_PLATFORM = "xcb";

  shellHook = ''
    echo "emulator at ${androidEmulator}"

    # Write out local.properties for Android Studio.
    cat <<EOF >| local.properties
    # This file was automatically generated by nix-shell.
    sdk.dir=$ANDROID_SDK_ROOT
    ndk.dir=$ANDROID_NDK_ROOT
    EOF
  '';
}
